### PR TITLE
fix: Validate chunk section Y axis upon retrieving ChunkRenderContainer

### LINKED ISSUE #587: Crash when flying to negative Y
### Reproduction Steps

1. Try to fall/fly under bedrock (negative Y)
2. The game crashes

### Crash Report File
[Crash report](https://gist.github.com/normannn/01a4bc2ecadfbf74486614155457b282)

### Additional Information
Compiled from next branch at [commit](https://github.com/CaffeineMC/sodium-fabric/commit/07c4cc1fd6a5b67f6fe08ee18db05d254a5051c4).

### PR DESCRIPTION
**Pull request by FlashyReese**
Fixes #587, the issue was present on https://github.com/CaffeineMC/sodium-fabric/commit/de545a500a31f96b5caf7f698a38902945e70f2e. The `ChunkRenderManager#isChunkVisible` was modified using the new `ChunkGraphCuller#isSectionVisible`  requiring a ChunkRenderContainer ID. Upon retrieving the `ChunkRenderContainer` with `ChunkRenderManager#getRender`, Sodium does not verify chunk section Y axis.

### CODE REVIEW

File: src/main/java/me/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager.java [hunk 1]
```diff
@@ -227,6 +227,10 @@ private void addEntitiesToRenderLists(ChunkRenderContainer render) {
     }
 
     public ChunkRenderContainer getRender(int x, int y, int z) {
+        if (y < 0 || y >= 16) {
```
Comment (magneticflux-) [inline src/main/java/me/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager.java]: This should probably check the array size instead of these constants for future-proofing.
```suggestion
        if (y < 0 || y >= this.columns.length) {
```

**Review by magneticflux- — CHANGES_REQUESTED** [review]

**Review by magneticflux- — APPROVED** [review]
