### PR TITLE
Efficient CPU Translucency Sorting with BSP Trees and Heuristics

### LINKED ISSUE #38: Translucent blocks do not render correctly (fixed in Sodium 0.6)
### Expected Behavior
Water will be visible inside glass stained pipes, commonly used in water elevators

### Actual Behavior
Water is not visible through stained glasses, although items can be seen flowing

### Reproduction Steps
Make a water tube, doesn't matter if its flowing or a water elevator type.

### Attachments
https://cdn.discordapp.com/attachments/389371678859460611/726798724206166066/received_707934516451025.png

### System Information
- Java Version: [Java 8 Update 251]
- CPU: [Intel Core i5-7200U]
- GPU: [Intel HD Graphics 620]

### PR DESCRIPTION
**Pull request by douira**
This PR implements efficient CPU translucency sorting. See https://hackmd.io/@douira100/sodium-sl-gfni for a slightly outdated but still useful overview of the concepts.

### Included in this PR
- Implementation of GFNI and direct (angle or distance) sort triggering
- Implementation of various sorting algorithms of increasing complexity (static normal relative, static topological, BSP tree, dynamic topological)
- User-facing debug info and option to turn it off or restrict to non-dynamic sorting only
- Index buffer rendering of translucent geometry
- Compatibility with Indium is implemented [in this branch](https://github.com/douira/Indium/tree/sodium-ts-gfni-compat)

Closes https://github.com/CaffeineMC/sodium-fabric/issues/38

### Non-goals
Translucency sorting on the GPU is certainly possible to be integrated with triggering with GFNI but not the focus of this PR. A first implementation of sorting on the CPU that works with GFNI is important to gauge performance of the triggering system and to enable the translucency sorting problem to be fixed without getting into the considerable effort of GPU sorting. Furthermore a CPU sorting implementation is needed in order to take advantage of the significant work-savings achievable by designating sections statically sorted.

My measurements indicate that triggering and sorting perform well, and usually beat distance-based sorting by either not needing to do any work, by doing the work more efficiently, or less often.

### CODE REVIEW

**Comment by ateijelo** [comment]
I checked out this PR's branch and built it with `./gradlew assemble` and using the resulting .jar, my game crashes when joining a world:
https://gist.github.com/ateijelo/d70f8ba8a026e238ee084785b7f480a7

**Comment by Lolothepro** [comment]
> I checked out this PR's branch and built it with `./gradlew assemble` and using the resulting .jar, my game crashes when joining a world: [gist.github.com/ateijelo/d70f8ba8a026e238ee084785b7f480a7](https://gist.github.com/ateijelo/d70f8ba8a026e238ee084785b7f480a7)

image

**Comment by douira** [comment]
Nobody should try to actually run this PR how it is currently, it does not to do what you think it does and it will not work until further work (outlined in the top comment) is done. I'm assuming you haven't even read what I wrote there, because if you did it would be clear that this is nowhere near functioning in a playable sense.

**Comment by Lolothepro** [comment]
#38

**Comment by douira** [comment]
Current work on getting this to render is being done on a separate branch until it starts to function at least a little bit. Currently rendering the index buffer does not work and things become corrupted in the render or crash. Help is appreciated. https://github.com/douira/sodium-fabric/tree/gfni-index-rendering

**Comment by CodeF53** [comment]
Given the current description of the PR, it seems like your implementation of the sorting algorithm is finished. If this is not the case, please disregard this comment and continue your excellent work.

By looking down on a vertical stream of water, you can see artifacts from improper sorting. This occurs where y%16 == 0
Looking down at a stream of water, artifact visible at y=-48

**Comment by douira** [comment]
It's not finished. It's finished when I make this PR a non-draft PR and announce that I'm looking for testing and code review. Thanks for the report though.

**Comment by douira** [comment]
While the work on this PR isn't complete, the "backend" is more or less stable at this point. I don't have any further plans to change the code that uploads and renders the index data. I'm interested in code reviews of the following classes (but also anything else, though note that I might still make changes to other parts)
- `DefaultChunkRenderer`
- `SectionRenderDataStorage`
- `SectionRenderDataUnsafe`
- `RenderRegion`
- `RenderRegionManager`
- `SodiumGameOptions`
- `SodiumGameOptionsPages`

Maybe the final review can be expedited somewhat if some of the independent parts can be discussed ahead of time. I'm open to any suggestions improving architecture, style, legibility, or performance. It's not yet time to mark the whole PR as ready to review, but it is in a state where testing for bugs is appreciated.

File: src/main/java/me/jellysquid/mods/sodium/client/render/chunk/DefaultChunkRenderer.java [hunk 1]
```diff
@@ -208,25 +246,48 @@ private static float getCameraTranslation(int chunkBlockPos, int cameraBlockPos,
...
-                TessellationBinding.forVertexBuffer(resources.getVertexBuffer(), new GlVertexAttributeBinding[] {
+                TessellationBinding.forVertexBuffer(resources.getGeometryBuffer(), new GlVertexAttributeBinding[] {
                         new GlVertexAttributeBinding(ChunkShaderBindingPoints.ATTRIBUTE_PACKED_DATA,
                                 this.vertexFormat.getAttribute(ChunkMeshAttribute.VERTEX_DATA))
                 }),
                 TessellationBinding.forElementBuffer(this.sharedIndexBuffer.getBufferObject())
         });
     }
 
+    private GlTessellation createIndexedRegionTessellation(CommandList commandList, RenderRegion.DeviceResources resources) {
```
Comment (embeddedt) [inline src/main/java/me/jellysquid/mods/sodium/client/render/chunk/DefaultChunkRenderer.java]: Can this be implemented as a `useSharedIndex` argument to `createRegionTessellation` instead?

File: src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java [hunk 2]
```diff
@@ -58,6 +62,91 @@ public interface ModelQuadView {
...
+        final float dz1 = z3 - z1;
+
+        float normX = dy0 * dz1 - dz0 * dy1;
+        float normY = dz0 * dx1 - dx0 * dz1;
+        float normZ = dx0 * dy1 - dy0 * dx1;
+
+        int packedNormal = -1;
+        if (calculateUnitNormal) {
+            // normalize by length for the packed normal
+            float length = (float) Math.sqrt(normX * normX + normY * normY + normZ * normZ);
```
Comment (MeeniMc) [inline src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java]: you are still at risk of dividing by "almost zero" which will create grossly inaccurate results

File: src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java [hunk 3]
```diff
@@ -58,6 +62,91 @@ public interface ModelQuadView {
...
+                normZ /= length;
+            }
+
+            packedNormal = NormI8.pack(normX, normY, normZ);
+        }
+
+        // normalize onto the surface of a cube by dividing by the length of the longest
+        // component
+        float infNormLength = Math.max(Math.abs(normX), Math.max(Math.abs(normY), Math.abs(normZ)));
+        if (infNormLength != 0 && infNormLength != 1) {
```
Comment (MeeniMc) [inline src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java]: you are still at risk of dividing by "almost zero" which will create grossly inaccurate results

File: src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java (hunk 2 above)
Comment (douira) [reply src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java]: this part of the code is actually just transferred from what sodium was doing previously. I don't know what this normal is used for or if that would be a problem.

File: src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java (hunk 3 above)
Comment (douira) [reply src/main/java/me/jellysquid/mods/sodium/client/model/quad/ModelQuadView.java]: This part is not Sodium's code but where I make my own (heavily quantized) normal for GFNI triggering and translucency sorting. Since I'm projecting onto the surface of a unit cube anyways, this is probably fine. Unless it generates non-unit length normals it doesn't really matter if the result is weird if the input is weird.

**Comment by douira** [comment]
Testing is happening in the Caffeine Discord server in [this thread.](https://discord.com/channels/602796788608401408/1188996660257366076)

**Comment by BigClarky** [comment]
I'm assuming the fix will not be back-ported to any 1.19.x versions

**Comment by douira** [comment]
Sodium's LTS version that is a back port of the main version targeting the latest MC is on 1.20.1 at the moment and would only get more recent if the focus of the modding community changes. I wouldn't expect an official version for 1.19.x but I can imagine it's doable.

**Comment by denny4-user** [comment]
Fix translucent_sorting for Sodium 0.5.10 / 0.5.11 ? Please
Fabric 1.20.1 *

**Comment by douira** [comment]
As per our [Support Policy](https://github.com/CaffeineMC/sodium/wiki/Support-Policy) 1.20.1 Fabric is not receiving new features.

Please do not comment on this PR
