### PR TITLE
Replace all critical memory code with Unsafe

### LINKED ISSUE #3554: Severe Performance issue on 26.1
This is easily reproduced with Iris but Vogon was able to reproduce with just sodium [here](https://discord.com/channels/602796788608401408/651120262129123330/1486811044067414167).
> so turns out I am able to trigger the problem with only sodium, and in Vanilla too. Its muuuuch worse in vanilla, but with sodium it can still take up like half the frametime. Here is vanilla at 48FPS with <50 entities. Normal FPS is around 900.

Image

> with Sodium it drops from >1K FPS to like 500 in this scene

Image

This is probably related to the switch to Java 25 where `VarHandle` and related mechanisms are apparently broken. This is in part, but not fully, a vanilla issue. (and also an iris issue)

### PR DESCRIPTION
**Pull request by IMS212**
Should fix #3554. Not a nice fix, but a fix.

### CODE REVIEW

File: neoforge/src/mod/java/net/caffeinemc/mods/sodium/mixin/platform/neoforge/EntrypointMixin.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
  */
 @Mixin(Minecraft.class)
 public class EntrypointMixin {
-    @Inject(method = "<init>", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/Options;loadSelectedResourcePacks(Lnet/minecraft/server/packs/repository/PackRepository;)V"))
+    @Inject(method = "<init>", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/Options;<init>(Lnet/minecraft/client/Minecraft;Ljava/io/File;)V", shift = At.Shift.AFTER))
```
Comment (douira) [inline neoforge/src/mod/java/net/caffeinemc/mods/sodium/mixin/platform/neoforge/EntrypointMixin.java:20]: is this change related to this PR?

File: common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/WindowMixin.java [hunk 2]
```diff
@@ -17,7 +17,7 @@
 import org.lwjgl.glfw.GLFW;
 import org.lwjgl.glfw.GLFWNativeWin32;
 import org.lwjgl.opengl.WGL;
-import org.lwjgl.system.MemoryUtil;
+import net.caffeinemc.mods.sodium.api.memory.MemoryIntrinsics;
```
Comment (douira) [inline common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/WindowMixin.java]: I don't think this import makes any sense?

File: common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/RenderSystemMixin.java [hunk 3]
```diff
@@ -18,6 +18,7 @@
 import net.minecraft.resources.Identifier;
 import org.lwjgl.glfw.GLFWNativeWin32;
 import org.lwjgl.opengl.WGL;
+import net.caffeinemc.mods.sodium.api.memory.MemoryIntrinsics;
```
Comment (douira) [inline common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/RenderSystemMixin.java]: this one also not

File: common/src/main/java/net/caffeinemc/mods/sodium/client/util/NativeBuffer.java [hunk 4]
```diff
@@ -6,6 +6,7 @@
 import net.caffeinemc.mods.sodium.client.SodiumClientMod;
 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
+import net.caffeinemc.mods.sodium.api.memory.MemoryIntrinsics;
```
Comment (douira) [inline common/src/main/java/net/caffeinemc/mods/sodium/client/util/NativeBuffer.java]: unused import

File: common/src/main/java/net/caffeinemc/mods/sodium/client/gl/shader/ShaderWorkarounds.java [hunk 5]
```diff
@@ -19,6 +19,7 @@
 import org.lwjgl.PointerBuffer;
 import org.lwjgl.opengl.GL20C;
 import org.lwjgl.system.MemoryStack;
+import net.caffeinemc.mods.sodium.api.memory.MemoryIntrinsics;
```
Comment (douira) [inline common/src/main/java/net/caffeinemc/mods/sodium/client/gl/shader/ShaderWorkarounds.java]: unused

File: buildSrc/src/main/kotlin/BuildConfig.kt [hunk 6]
```diff
@@ -2,7 +2,7 @@
 
 object BuildConfig {
     val MINECRAFT_VERSION: String = "26.1"
-    val NEOFORGE_VERSION: String = "26.1.0.0-alpha.0+rc-3.20260323.185344"
```
Comment (douira) [inline buildSrc/src/main/kotlin/BuildConfig.kt]: is this change related to this PR?

File: common/src/api/java/net/caffeinemc/mods/sodium/api/memory/MemoryIntrinsics.java [hunk 7]
```diff
@@ -1,11 +1,13 @@
 package net.caffeinemc.mods.sodium.api.memory;
 
+import org.lwjgl.system.Pointer;
 import sun.misc.Unsafe;
 
 import java.lang.reflect.Field;
 
 public class MemoryIntrinsics {
     private static final Unsafe UNSAFE;
+    private static final boolean BITS32 = Pointer.BITS32;
```
Comment (douira) [inline common/src/api/java/net/caffeinemc/mods/sodium/api/memory/MemoryIntrinsics.java:10]: do we have validation that sodium actually works in 32 bit mode?

**Review by douira — CHANGES_REQUESTED** [review]

File: neoforge/src/mod/java/net/caffeinemc/mods/sodium/mixin/platform/neoforge/EntrypointMixin.java (hunk 1 above)
Comment (IMS212) [reply neoforge/src/mod/java/net/caffeinemc/mods/sodium/mixin/platform/neoforge/EntrypointMixin.java:20]: No, but required for the NeoForge version to run. Was forgotten in 0.8.7.

File: common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/WindowMixin.java (hunk 2 above)
Comment (IMS212) [reply common/src/main/java/net/caffeinemc/mods/sodium/mixin/workarounds/context_creation/WindowMixin.java]: Find/replace bug. Will fix.

File: common/src/api/java/net/caffeinemc/mods/sodium/api/memory/MemoryIntrinsics.java (hunk 7 above)
Comment (IMS212) [reply common/src/api/java/net/caffeinemc/mods/sodium/api/memory/MemoryIntrinsics.java:10]: No, however the behavior here is copied identically from old MemoryUtil.

File: buildSrc/src/main/kotlin/BuildConfig.kt (hunk 6 above)
Comment (douira) [reply buildSrc/src/main/kotlin/BuildConfig.kt]: would you mind making a separate commit for the neoforge update?

**Review by douira — APPROVED** [review]
