### PR TITLE
fix: Broken block and fluid animations

### LINKED ISSUE #458: Only animate visible textures not animating any textures when enabled
### Expected Behavior
All visible textures should be animated

### Actual Behavior
No textures are animated.

### Reproduction Steps
Turn on Only Animate Visible Textures. Look at a block that has an animated texture (water or lava). Note, the only way to fix this (without coding) is to disable it in the settings. To be honest, there wasn't any performance impact when disabling it.

### Attachments
I am using the latest Next release from Github. d352852 to be exact.

### System Information
- Java Version: [15.0.1 ]
- CPU: [AMD FX 8350]
- GPU: [AMD Radeon RX 480]

### PR DESCRIPTION
**Pull request by Grayray75**
This fixes broken block and fluid animations when **Animate Only Visible Textures** is enabled.

Closes: #458

### CODE REVIEW

File: src/main/java/me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer.java [hunk 1]
```diff
@@ -105,14 +106,14 @@ private void renderQuadList(BlockRenderView world, BlockState state, BlockPos po
...
-            this.renderQuad(world, state, pos, sink, offset, colorizer, quad, light);
+            this.renderQuad(world, state, pos, sink, offset, buffers, colorizer, quad, light);
         }
 
         sink.flush();
     }
 
     private void renderQuad(BlockRenderView world, BlockState state, BlockPos pos, ModelVertexSink sink, Vec3d offset,
-                            BlockColorProvider colorProvider, BakedQuad bakedQuad, QuadLightData light) {
+                            ChunkModelBuffers buffers, BlockColorProvider colorProvider, BakedQuad bakedQuad, QuadLightData light) {
```
Comment (jellysquid3) [inline src/main/java/me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer.java]: This should simply pass the `ChunkRenderData.Builder` type directly to avoid `getRenderData()` calls below. We shouldn't need to access anything else on `ChunkModelBuffers`, anyways.

**Comment by jellysquid3** [comment]
LGTM, this is basically what we did anyways, just never copied it into the new types during the vertex system changes.
