### PR TITLE
Fix Fluid Occlusion For Waterlogged Blocks

### LINKED ISSUE #2699: Water is not rendered in some cases with Framed Blocks (occlusion when waterlogged)
### Bug Description

Water is not rendered in some cases with Framed Blocks (occlusion when waterlogged)

### Reproduction Steps

Place the “Framed Inner Corner Slope” frame from Framed Blocks, and waterlog it.

### Log File

https://mclo.gs/U5BAsH9

### Crash Report

*

### PR DESCRIPTION
**Pull request by douira**
Fixes fluid occlusion by using voxel shape comparison with the waterlogged block using BlockOcclusionCache. Using `isFaceSturdy` was wrong for occlusion purposes since it deals with hitboxes and not what is rendered. Thanks to @XFactHD for clearing this up.

Fixes https://github.com/CaffeineMC/sodium/issues/2699

I've also made a [1.21.1 branch of this](https://github.com/douira/sodium/tree/fix-fluid-occlusion) for testing purposes since FramedBlocks, which I was using to reproduce the issue, isn't available on the latest Minecraft version that `dev` uses. When backporting this to 1.21.1, you can use [the commit on that branch](https://github.com/douira/sodium/commit/8ddfd0ca634de58800b42be8d2b112590a6676f8), which slightly differs because of changes to `getFaceOcclusionShape`.

From my testing it doesn't regress the other fluid occlusion issue https://github.com/CaffeineMC/sodium/issues/2606. Visual discontinuities arising from water flowing along a row of slabs getting culled suddenly once its height goes below half a block are normal and exist in both upstream Sodium and vanilla.

### CODE REVIEW

File: common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache.java [hunk 1]
```diff
@@ -88,6 +89,75 @@ private static boolean isEmptyShape(VoxelShape voxelShape) {
...
+
+        // only occlude against blocks that can potentially occlude in the first place
+        if (!otherState.canOcclude()) {
+            return true;
+        }
+
+        var otherShape = otherState.getFaceOcclusionShape(facing.getOpposite());
+
+        // If the other block has an empty cull shape, then it cannot hide any geometry
+        if (otherShape.isEmpty()) {
```
Comment (jellysquid3) [inline common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache.java]: `VoxelShape#isEmpty` can be slow since it involves many virtual dispatches and pointer chases. There should be a check for `shape == Shapes.empty()` before calling it.

File: common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache.java [hunk 2]
```diff
@@ -88,6 +89,75 @@ private static boolean isEmptyShape(VoxelShape voxelShape) {
...
+     */
+    public boolean shouldDrawFullBlockFluidSide(BlockState selfBlockState, BlockGetter view, BlockPos selfPos, Direction facing, FluidState fluid, VoxelShape fluidShape) {
+        var fluidShapeIsBlock = fluidShape == Shapes.block();
+
+        // only perform self-occlusion if the own block state can't occlude
+        if (selfBlockState.canOcclude()) {
+            var selfShape = selfBlockState.getFaceOcclusionShape(facing);
+
+            // only a non-empty self-shape can occlude anything
+            if (!selfShape.isEmpty()) {
```
Comment (jellysquid3) [inline common/src/main/java/net/caffeinemc/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache.java]: See comment about `VoxelShape#isEmpty`. Probably there should be a utility function to check if the shape is empty.

**Review by jellysquid3 — CHANGES_REQUESTED** [review]

**Comment by jellysquid3** [comment]
This patch looks good outside of the aforementioned comments.

**Comment by douira** [comment]
Resolved review items by using the existing utility methods that check for empty or full shapes.

**Review by jellysquid3 — APPROVED** [review]

**Comment by jellysquid3** [comment]
Thanks!
